# Generic train terms
dataset_id: "coco"
target_batch_size: 256
batch_size: 64
val_batch_mult: 2
grad_clip: -1
epochs: 100

# Saving and intervals
checkpoint_root_dir: "checkpoints/control_pred/"
log_interval: 1
sample_interval: 100
save_interval: 20000
val_interval: 1000
resume: false

# optimizer and scheduler
opt: "AdamW"
opt_kwargs:
  lr: 1.0e-4
  eps: 1.0e-15
  betas: [0.9, 0.95]
  weight_decay: 0.1

scheduler: null
scheduler_kwargs:
  warmup_steps: 150

# Logging
run_name: "first attempt"
wandb_entity: "shahbuland"
wandb_project: "control_pred"
